services:
  web:
    build: ./flask
    ports:
      - "8080:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=
      - OPENAI_API_KEY=
    depends_on:
      - db
      - mq
    restart: always

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  mq:
    build: ./rabbitmq
    ports:
      - "61613:61613"
      - "15672:15672"
      - "15674:15674"
    restart: always
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./project:/usr/share/nginx/html:ro
    restart: always